@hostname = http://localhost
@port = 8080
@host = {{hostname}}:{{port}}/api
@contentType = application/json; charset=utf-8
@Authorization = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTE2NDU2MTcsImp0aSI6IjYiLCJuYW1lIjoic2FtcGxlMSIsInVpZCI6Nn0.5wimnISr1yn0Jb73GPSSE8kYH1j-bEv8huzdqL5EV4Y

# @name
POST {{host}}/post HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{Authorization}}

{
    "title": "Test Post 1",
    "content": "This is a test post 1",
    "IsRecommend": 2,
}

###
DELETE {{host}}/post/37 HTTP/1.1
Authorization: Bearer {{Authorization}}

###
POST {{host}}/like/post/:id HTTP/1.1
Authorization: Bearer {{Authorization}}

###
DELETE  {{host}}/like/post/:id HTTP/1.1
Authorization: Bearer {{Authorization}}
