version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    platform: linux/amd64
    # image: mysql/mysql-server # Apple M1
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    command: --default-authentication-plugin=mysql_native_password

    ports:
      - ${MYSQL_PORT}:3306
    expose:
      - 3306
    volumes:
      # - ./docker/mysql:/var/lib/mysql
      - ./docker/import:/docker-entrypoint-initdb.d
      - ./docker/mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$MYSQL_ROOT_PASSWORD']
      timeout: 20s
      retries: 5

  backend:
    # image: shiyiya/yszm-api:0.0.1
    container_name: app
    build: .
    restart: always
    ports:
      - ${APP_PORT}:8080
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
