version: '3.7'

services:
  backend:
    container_name: app
    build: .
    restart: always
    ports:
      - ${APP_PORT}:8080
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    platform: linux/amd64
    # image: mysql/mysql-server # Apple M1
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    ports:
      - ${MYSQL_PORT}:3306
    expose:
      - 3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/import:/docker-entrypoint-initdb.d


    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}